<a href="https://colab.research.google.com/github/NadaMagdy-hub/Interactive-Bike-Sales-Dashboard/blob/main/sellers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import unicodedata
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
sellers = pd.read_csv('/content/olist_sellers_dataset.csv')

In [ ]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [ ]:
sellers.tail()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [ ]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [ ]:
sellers.shape

(3095, 4)

In [ ]:
sellers.isnull()

      seller_id  seller_zip_code_prefix  seller_city  seller_state
0         False                   False        False         False
1         False                   False        False         False
2         False                   False        False         False
3         False                   False        False         False
4         False                   False        False         False
...         ...                     ...          ...           ...
3090      False                   False        False         False
3091      False                   False        False         False
3092      False                   False        False         False
3093      False                   False        False         False
3094      False                   False        False         False

[3095 rows x 4 columns]

In [ ]:
sellers.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [ ]:
sellers.duplicated().sum()

np.int64(0)

In [ ]:
sellers.describe()

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

----تنظيف أسماء المدن (Lowercase و شيل المسافات)-------

In [ ]:
sellers['seller_city'] = sellers['seller_city'].astype(str).str.strip().str.lower()

---- تحويل الولايات لحروف كبيرة (Uppercase) عشان تطابق ملف الجيولكيشن بالظبط (SP, RJ...)-----

In [ ]:
sellers['seller_state'] = sellers['seller_state'].astype(str).str.strip().str.upper()

-----نسيب الـ Zip Code كـ Integer (رقم) زي ملف الجيولكيشن عشان يربطوا صح------

In [ ]:
sellers['seller_zip_code_prefix'] = sellers['seller_zip_code_prefix'].astype(int)

In [ ]:
sellers.seller_id.duplicated().sum()

np.int64(0)

In [ ]:
sellers.to_csv('cleaned_sellers.csv', index=False)